"""empty message

Revision ID: fd7e0d45d8e2
Revises: 
Create Date: 2019-03-20 01:22:23.430111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7e0d45d8e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lexology',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('profile_info', sa.TEXT(), nullable=True),
    sa.Column('social', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lexology')
    # ### end Alembic commands ###
